var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/services/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j048-b._.js")
R.c("server/chunks/ssr/mnt_gO_Opti_0qq838.._.js")
R.c("server/chunks/ssr/0bh9_next_dist_esm_build_templates_app-page_06~3x6o.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~p.up9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hx7ejd._.js")
R.c("server/chunks/ssr/mnt_gO_Opti_10ndspf._.js")
R.c("server/chunks/ssr/0bh9_next_dist_client_components_0aabhpj._.js")
R.c("server/chunks/ssr/0bh9_next_dist_client_components_builtin_forbidden_0.7-9~4.js")
R.c("server/chunks/ssr/0bh9_next_dist_client_components_builtin_unauthorized_0_qg7m2.js")
R.c("server/chunks/ssr/0bh9_next_dist_client_components_builtin_global-error_05tr9lf.js")
R.c("server/chunks/ssr/mnt_gO_Opti__next-internal_server_app_services_[slug]_page_actions_13qh6ma.js")
R.m(24419)
module.exports=R.m(24419).exports
