var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/services/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lqg30n._.js")
R.c("server/chunks/ssr/goopti-next_0ora81z._.js")
R.c("server/chunks/ssr/01gr_next_dist_esm_build_templates_app-page_10d0qlz.js")
R.c("server/chunks/ssr/[root-of-the-server]__13u9i~d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o~v8ja._.js")
R.c("server/chunks/ssr/goopti-next_0tqsedj._.js")
R.c("server/chunks/ssr/01gr_next_dist_client_components_0sx3pwm._.js")
R.c("server/chunks/ssr/01gr_next_dist_client_components_builtin_forbidden_0qpgvfl.js")
R.c("server/chunks/ssr/01gr_next_dist_client_components_builtin_unauthorized_0kilprq.js")
R.c("server/chunks/ssr/01gr_next_dist_client_components_builtin_global-error_0wtuy_y.js")
R.c("server/chunks/ssr/goopti-next__next-internal_server_app_services_[slug]_page_actions_0eab--_.js")
R.m(85762)
module.exports=R.m(85762).exports
